### ISSUE TITLE
Doesn't respect regex file paths

### ISSUE THREAD

**Issue by artivilla** [cdeutsch/webpack-shell-plugin-alt#4]
The current files don't get removed:
```
onBuildStart: [`rm -rf ${path.resolve(__dirname, '../src/main/resources/config/*.client-script-manifest.json')}`, `rm -rf ${buildPath}`],
```

**Comment by cdeutsch** [comment]
I don't think that's related to this library.

It's just executing what you tell it via `spawn` or `exec`
https://github.com/cdeutsch/webpack-shell-plugin-alt/blob/91bd9f13698b34801a694a6b562d2ffabbb7f214/src/webpack-shell-plugin.js#L40

I could be wrong, I didn't write this originally, so reopen if you think otherwise.
